### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by pmsobrado**
Just changing c for C :)

### CODE REVIEW

**Comment by suraj0208** [comment]
Thank you but there is no need to do this. The original button is named 'Call' I kept it 'call' to tell the difference.

**Comment by pmsobrado** [comment]
2016-10-20 12:06 GMT+02:00 Suraj <notifications@github.com>:

>

> you but there is no need to do this. The original button is named 'Call'
I kept it 'call' to tell the difference.

Sorry but at least on my phone I see only yours, the WA one is outside,
check the screenshots:

Anyway, maybe you could go with "Cell call" or something, I know it's silly
but seeing all the words with capitals but yours annoy me a bit :S

* Pablo Manuel Sobrado Gómez*
Projects area - Devops * Emergya Consultoría*
Tfno: +34 954 51 75 77
Fax: +34 954 51 64 73
www.emergya.es

**Comment by suraj0208** [comment]
You can long press the original one to see its title ( toast appears at bottom ). It does have a title even if you dont see it. In the next release I've added the replacement option so from next version you can disable the 'call' from menu. ok ?

**Comment by pmsobrado** [comment]
I'll check next version. Did you check my second cap? You can see the menu
openened and the "call" string.

**Comment by suraj0208** [comment]
Sorry but I didnt understand what you mean by 'second cap'. also explain 'You can see the menu openened and the "call" string.'

**Comment by pmsobrado** [comment]
Didnt you check the attached screenshots? thats what I meant :)

**Comment by suraj0208** [comment]
I did not receive screenshot

**Comment by pmsobrado** [comment]
Im sorry, I attached them on gmail. I'll try later

**Comment by pmsobrado** [comment]
Did you get the screenshots?



* Pablo Manuel Sobrado Gómez*
 Projects area - Devops
 * Emergya Consultoría*
 Tfno: +34 954 51 75 77
 Fax: +34 954 51 64 73
 www.emergya.es


2016-10-20 20:54 GMT+02:00 Pablo Sobrado Gómez <pmsobrado@emergya.com>:

> There you go:
>
> https://drive.google.com/file/d/0B9pc9wI3CiMMR3Jzel9XMkpRM3R3e
> W1SazJHWGRkOGpoem5r/view?usp=sharing
>
> https://drive.google.com/file/d/0B9pc9wI3CiMMWVBibGNwQzIwNGlEW
> EJXbXU0TS1RNF9zLWZV/view?usp=sharing
>
>
>
> * Pablo Manuel Sobrado Gómez*
>  Projects area - Devops
>  * Emergya Consultoría*
>  Tfno: +34 954 51 75 77
>  Fax: +34 954 51 64 73
>  www.emergya.es
>
>
> 2016-10-20 17:58 GMT+02:00 Pablo Sobrado Gómez <pmsobrado@emergya.com>:
>
>> Im sorry, I attached them on gmail. I'll try later
>>

**Comment by pmsobrado** [comment]
There you go:

https://drive.google.com/file/d/0B9pc9wI3CiMMR3Jzel9XMkpRM3R3eW1SazJHWGRkOGpoem5r/view?usp=sharing

https://drive.google.com/file/d/0B9pc9wI3CiMMWVBibGNwQzIwNGlEWEJXbXU0TS1RNF9zLWZV/view?usp=sharing



* Pablo Manuel Sobrado Gómez*
 Projects area - Devops
 * Emergya Consultoría*
 Tfno: +34 954 51 75 77
 Fax: +34 954 51 64 73
 www.emergya.es


2016-10-20 17:58 GMT+02:00 Pablo Sobrado Gómez <pmsobrado@emergya.com>:

> Im sorry, I attached them on gmail. I'll try later
>

**Comment by suraj0208** [comment]
just wait for next version. I'll update this week.

**Comment by pmsobrado** [comment]
Ok thanks.

**Comment by suraj0208** [comment]
See the new version. If you are satisfied with the replace functionality close the pull request. I'm sorry it cannot be changed to 'call' it has to be 'Call'

**Comment by pmsobrado** [comment]
I still can see the call string without the uppercase, but with the replace
call button option that doesn't happen anymore, thanks!



* Pablo Manuel Sobrado Gómez*
 Projects area - Devops
 * Emergya Consultoría*
 Tfno: +34 954 51 75 77
 Fax: +34 954 51 64 73
 www.emergya.es


2016-11-01 17:13 GMT+01:00 Suraj <notifications@github.com>:

**Pull request closed without merging**
