### PR TITLE
Added Turkish Language

### PR DESCRIPTION
**Pull request by edorewiel**
Added Turkish Language

### CODE REVIEW

**Comment by suraj0208** [comment]
thanks for translating.Did you translate according to what I specified on the XDA thread ? menuitem_call still says 'call' is it correct?

**Comment by edorewiel** [comment]
oh my mistake. 
Fixed.

**Comment by suraj0208** [comment]
You didnt translate according to what I said on the forums. I checked on my phone and found the 'Forward' string in onclickactions was not properly translated. I corrected it. Please follow my instructions. Thank you. Merging the commits.

**Comment by suraj0208** [comment]
can you update your translations for Turkish. I've added comments in english xml where translations are needed ( end of xml file ). Thank you. 
Please reply otherwise I'll have to wait unnecessarily.

**Pull request merged**
