### PR TITLE
fix nougat

### PR DESCRIPTION
**Pull request by Jasi2169**
fix nougat issue

### CODE REVIEW

**Comment by Jasi2169** [comment]
i only made this change and it worked fine because i believe people will come to mainactivity which will be the last activity to be paused or destroyed

rather then writing same code you can call this function anytime to make changes to prefs by passing context

public void makeread(Context c){
c.getpackagename bla bla

but that is not rerquired

**Comment by Jasi2169** [comment]
@suraj0208 did you compiled it ? my nougat fix is working fine

many modules are broken and my one line is fixing it i am modifying many modules privately myself all working fine

**Comment by suraj0208** [comment]
I'm trying it. I'll get back to you.

**Review by minhhhhhhh — APPROVED** [review]

**Comment by gokulraj3** [comment]
I am getting error with the custom wallpaper, it works untill selection of image and croping it. But when I click done it just crashes.!! And also the lock is not working now

**Pull request closed without merging**
